/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author LUIS FANDIÑO
 */
public class MainView extends javax.swing.JFrame {
    
    private int id_Sede;
    /**
     * Creates new form MainView
     */
    public MainView(String cargo, int id_Sede) {
       this.id_Sede=id_Sede;
        initComponents();
        

    switch (cargo) {
    case "Admin":
        // ✅ El admin ve todas las opciones
        break;
    case "Inventario":
        switch (id_Sede) {
            case 1:
                jMenuVentas.setVisible(false);
                jMenuClientes.setVisible(false);
                jMenuEstadisticas.setVisible(false);
                break;
            case 2:
                jMenuVentas.setVisible(false);
                jMenuClientes.setVisible(false);
                jMenuEstadisticas.setVisible(false);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Sede no válida");
                dispose();
                break;
        }
        break;
    case "Vendedor":
        switch (id_Sede) {
            case 1:
                
                jMenuProveedores.setVisible(false);
                jMenuEstadisticas.setVisible(false);
                break;
            case 2:
                
                jMenuProveedores.setVisible(false);
                jMenuEstadisticas.setVisible(false);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Sede no válida");
                dispose();
                break;
        }
        break;
    default:
        JOptionPane.showMessageDialog(this, "Rol no válido");
        dispose(); // Cierra la ventana si el rol es inválido
        break;
}

setVisible(true);
    
    jMenuVerProductos.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e) {
              
               VerProductosView verProductosView= new VerProductosView(id_Sede, cargo);
               verProductosView.setVisible(true);
           }
        
    });
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuProductos = new javax.swing.JMenu();
        jMenuVerProductos = new javax.swing.JMenuItem();
        jMenuVentas = new javax.swing.JMenu();
        VerVentas = new javax.swing.JMenuItem();
        RegistrarVenta = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        VerClientes = new javax.swing.JMenuItem();
        jMenuProveedores = new javax.swing.JMenu();
        VerProveedores = new javax.swing.JMenuItem();
        RegistrarProveedor = new javax.swing.JMenuItem();
        jMenuEstadisticas = new javax.swing.JMenu();
        ProductoMásVendido = new javax.swing.JMenuItem();
        ProductoMenosVendido = new javax.swing.JMenuItem();
        CerrarSesión = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuProductos.setText("Productos");
        jMenuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProductosActionPerformed(evt);
            }
        });

        jMenuVerProductos.setText("Ver Productos");
        jMenuVerProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVerProductosMouseClicked(evt);
            }
        });
        jMenuVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerProductosActionPerformed(evt);
            }
        });
        jMenuProductos.add(jMenuVerProductos);

        jMenuBar.add(jMenuProductos);

        jMenuVentas.setText("Ventas");

        VerVentas.setText("Ver Ventas");
        jMenuVentas.add(VerVentas);

        RegistrarVenta.setText("Registrar Venta");
        RegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarVentaActionPerformed(evt);
            }
        });
        jMenuVentas.add(RegistrarVenta);

        jMenuBar.add(jMenuVentas);

        jMenuClientes.setText("Clientes");

        VerClientes.setText("Ver Clientes");
        jMenuClientes.add(VerClientes);

        jMenuBar.add(jMenuClientes);

        jMenuProveedores.setText("Proveedores");

        VerProveedores.setText("Ver Proveedores");
        jMenuProveedores.add(VerProveedores);

        RegistrarProveedor.setText("Registrar Proveedor");
        jMenuProveedores.add(RegistrarProveedor);

        jMenuBar.add(jMenuProveedores);

        jMenuEstadisticas.setText("Estadisticas");

        ProductoMásVendido.setText("Producto Más Vendido");
        ProductoMásVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoMásVendidoActionPerformed(evt);
            }
        });
        jMenuEstadisticas.add(ProductoMásVendido);

        ProductoMenosVendido.setText("Producto Menos Vendido");
        ProductoMenosVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoMenosVendidoActionPerformed(evt);
            }
        });
        jMenuEstadisticas.add(ProductoMenosVendido);

        jMenuBar.add(jMenuEstadisticas);

        CerrarSesión.setText("Cerrar sesión");
        CerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesiónMouseClicked(evt);
            }
        });
        CerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesiónActionPerformed(evt);
            }
        });
        jMenuBar.add(CerrarSesión);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerProductosActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jMenuVerProductosActionPerformed

    private void RegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarVentaActionPerformed

    private void ProductoMásVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoMásVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoMásVendidoActionPerformed

    private void ProductoMenosVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoMenosVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoMenosVendidoActionPerformed

    private void CerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesiónActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CerrarSesiónActionPerformed

    private void CerrarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesiónMouseClicked
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas cerrar sesión?",
                "Cerrar Sesion", JOptionPane.YES_NO_OPTION);
        
        if (confirmar==JOptionPane.YES_NO_OPTION) {
            this.dispose();
            new LoginView().setVisible(true);
                    
        }
    }//GEN-LAST:event_CerrarSesiónMouseClicked

    private void jMenuVerProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVerProductosMouseClicked
      
        
    }//GEN-LAST:event_jMenuVerProductosMouseClicked

    private void jMenuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuProductosActionPerformed
private void configurarMenuPorRol() {
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CerrarSesión;
    private javax.swing.JMenuItem ProductoMenosVendido;
    private javax.swing.JMenuItem ProductoMásVendido;
    private javax.swing.JMenuItem RegistrarProveedor;
    private javax.swing.JMenuItem RegistrarVenta;
    private javax.swing.JMenuItem VerClientes;
    private javax.swing.JMenuItem VerProveedores;
    private javax.swing.JMenuItem VerVentas;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuEstadisticas;
    private javax.swing.JMenu jMenuProductos;
    private javax.swing.JMenu jMenuProveedores;
    private javax.swing.JMenu jMenuVentas;
    private javax.swing.JMenuItem jMenuVerProductos;
    // End of variables declaration//GEN-END:variables

    private void configureView(String role, int sede) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
